"""Central path configuration for all MIMIC-IV data files."""

import os

DATA_ROOT = "/Users/skku_aws2_05/Documents/pre_project"

# MIMIC-IV directories (colon in dir names — Python handles fine)
MIMIC_HOSP = os.path.join(DATA_ROOT, "mimic-iv", "hosp:")
MIMIC_ICU = os.path.join(DATA_ROOT, "mimic-iv", "icu:")
MIMIC_NOTES = os.path.join(DATA_ROOT, "MIMIC-IV Note data", "note:")

# Project output
PROJECT_ROOT = os.path.join(DATA_ROOT, "lab_data")
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "output")
COHORT_DIR = os.path.join(OUTPUT_DIR, "cohort")
PROCESSED_DIR = os.path.join(OUTPUT_DIR, "processed")
REPORTS_DIR = os.path.join(OUTPUT_DIR, "reports")

# ─── MIMIC-IV hosp files ───
LABEVENTS = os.path.join(MIMIC_HOSP, "labevents.csv")
LABEVENTS_GZ = os.path.join(MIMIC_HOSP, "labevents.csv.gz")
D_LABITEMS = os.path.join(MIMIC_HOSP, "d_labitems.csv")
MICROBIOLOGYEVENTS = os.path.join(MIMIC_HOSP, "microbiologyevents.csv")
DIAGNOSES_ICD_GZ = os.path.join(MIMIC_HOSP, "diagnoses_icd.csv.gz")
D_ICD_DIAGNOSES = os.path.join(MIMIC_HOSP, "d_icd_diagnoses.csv")
D_ICD_PROCEDURES = os.path.join(MIMIC_HOSP, "d_icd_procedures.csv")
ADMISSIONS = os.path.join(MIMIC_HOSP, "admissions.csv")
PATIENTS = os.path.join(MIMIC_HOSP, "patients.csv")
PRESCRIPTIONS_GZ = os.path.join(MIMIC_HOSP, "prescriptions.csv.gz")

# ─── MIMIC-IV ICU files ───
CHARTEVENTS = os.path.join(MIMIC_ICU, "chartevents.csv")
CHARTEVENTS_GZ = os.path.join(MIMIC_ICU, "chartevents.csv.gz")
D_ITEMS = os.path.join(MIMIC_ICU, "d_items.csv")
ICUSTAYS_GZ = os.path.join(MIMIC_ICU, "icustays.csv.gz")

# ─── MIMIC-IV Note files ───
RADIOLOGY_NOTES = os.path.join(MIMIC_NOTES, "radiology.csv")
RADIOLOGY_DETAIL = os.path.join(MIMIC_NOTES, "radiology_detail.csv")
DISCHARGE_NOTES = os.path.join(MIMIC_NOTES, "discharge.csv")
DISCHARGE_DETAIL = os.path.join(MIMIC_NOTES, "discharge_detail.csv")

# ─── Output parquet files (generated by loaders) ───
CHEST_RADIOLOGY_PARQUET = os.path.join(COHORT_DIR, "chest_radiology.parquet")
DISCHARGE_CC_PARQUET = os.path.join(COHORT_DIR, "discharge_chief_complaints.parquet")
LUNG_LABS_PARQUET = os.path.join(COHORT_DIR, "lung_labs.parquet")
RESPIRATORY_VITALS_PARQUET = os.path.join(COHORT_DIR, "respiratory_vitals.parquet")
RESPIRATORY_MICRO_PARQUET = os.path.join(COHORT_DIR, "respiratory_micro.parquet")
LUNG_COHORT_PARQUET = os.path.join(COHORT_DIR, "lung_cohort.parquet")

# ─── Lung-relevant lab itemids ───
# Blood Gas
BLOOD_GAS_ITEMS = [50801, 50802, 50803, 50804, 50813, 50818, 50820, 50821, 50825, 50826]
# CBC with Differential
CBC_ITEMS = [51300, 51301, 51256, 51244, 51200, 51146, 51222, 51265, 51279, 51277]
# Inflammatory markers
INFLAMMATORY_ITEMS = [50889, 51652, 50893]  # CRP, Procalcitonin, ESR
# Chemistry (lung-relevant)
CHEMISTRY_ITEMS = [50862, 50882, 50902, 50912, 50915, 50924, 50931, 50954, 50960, 50963, 50971, 50983, 51002, 51003, 51006, 51288]
# Coagulation (PE relevant)
COAG_ITEMS = [51196, 51214, 51237, 51274]  # D-dimer, PT, INR, Fibrinogen
# Cardiac markers (PE/CHF)
CARDIAC_ITEMS = [50911, 50963, 51002, 51003]  # BNP, NT-proBNP, Troponin

LUNG_LAB_ITEMIDS = set(
    BLOOD_GAS_ITEMS + CBC_ITEMS + INFLAMMATORY_ITEMS +
    CHEMISTRY_ITEMS + COAG_ITEMS + CARDIAC_ITEMS
)

# ─── Lung-relevant ICU chartevents itemids ───
RESPIRATORY_CHART_ITEMS = {
    220210,  # Respiratory Rate
    220277,  # SpO2
    223835,  # FiO2 (Inspired O2 Fraction)
    220339,  # PEEP
    224684, 224685, 224686,  # Tidal Volume (observed, set, spontaneous)
    224690,  # Minute Volume
    223986, 223987, 223988, 223989,  # Lung Sounds (LUL, LLL, RUL, RLL)
    226873,  # Ventilator Mode
    226732,  # O2 Delivery Device
    220235,  # Peak Inspiratory Pressure
    224696,  # Plateau Pressure
    220045,  # Heart Rate (supportive)
    220179, 220180,  # BP Systolic, Diastolic (supportive)
    223761, 223762,  # Temperature F, C
}

# ─── Respiratory specimen types for microbiology ───
RESPIRATORY_SPECIMENS = {
    "SPUTUM", "BRONCHOALVEOLAR LAVAGE", "PLEURAL FLUID",
    "BRONCHIAL WASHINGS", "MINI-BAL", "BRONCHIAL BRUSH",
    "TRACHEAL ASPIRATE", "Rapid Respiratory Viral Screen & Culture",
    "THROAT CULTURE", "THROAT FOR STREP",
}

# ─── Chest X-ray exam name patterns ───
CHEST_EXAM_PATTERNS = [
    "CHEST", "CXR", "THORAX", "LUNG", "PULMONARY",
    "PA AND LAT", "PORTABLE AP", "CT CHEST",
]
